### ISSUE TITLE
Unexisting Directories Bug Report

### ISSUE THREAD

**Issue by Eyyyron** [Benny-Gil/OSA-System#1]
**Description of Bug**
The bug originated from the repository's unexisting directories.

**To Reproduce**
1. Go to and run 'app.py'.
2. Click on the IP address shown in the command line interface.
3. See the error on the command line interface and the website.

**Expected behavior**
The system should be able to properly run the index.html with its corresponding CSS file in the browser as shown in the image below.
![image](https://github.com/user-attachments/assets/5b261bf9-497b-48db-93d8-7493ce5097b3)

**Screenshots of Bug**
![image](https://github.com/user-attachments/assets/41f0a202-d966-4d71-8ee0-b65de5844e4a)

**Desktop**
 - OS: Microsoft Windows 10 Home Single Language (Version: 10.0.19045 Build 19045)
 - Browser: Opera GX
 - Version: LVL 6 (core: 114.0.5282.233)

**How to Fix**
1. Create directories named 'static' and 'templates' under the root directory
2. Move the style.css into the static directory
3. Move the index.html into the templates directory
4. Rename the href file path of style.css under the index.html

**Comment by Benny-Gil** [comment]
The issue has been resolved. The directory structure and file organization have been corrected. The application now properly loads index.html with its corresponding CSS file in the browser. You can verify the fix by running the system again. This functionality is now ready for use.
